name: Download YouTube Playlist

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "YouTube Video URL"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Create downloads directory
        run: mkdir -p downloads

      # - name: Download playlist
      #   run: |
      #     yt-dlp \
      #       -o "downloads/%(playlist_index)s - %(title)s.%(ext)s" \
      #       --yes-playlist \
      #       --ignore-errors \
      #       "${{ github.event.inputs.playlist_url }}"

      - name: Download video
        run: |
          yt-dlp --cookies-from-browser chrome \
          -f "bv*+ba/b" \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.video_url }}"

      - name: Debug - List files
        run: |
          echo "Contents of workspace:"
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: playlist-files
          path: downloads
          if-no-files-found: warn
