name: Download YouTube Video

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download video
        run: |
          yt-dlp --cookies-from-browser chrome \
          -f "bv*+ba/b" \
          -o "downloads/%(title)s.%(ext)s" \
          https://www.youtube.com/watch?v=VIDEO_ID

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: downloads/*
